// Game Database - RAW_DB
// This file contains all game data organized by category
// Game Database - RAW_DB
// This file contains all game data organized by category

const RAW_DB = {
  "Game PC": [
    // Data Asli dari database.js
    { "title": "A Plague Tale - innocence", "size": "11 GB", "location": "Fidelius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "A Plague Tale - Requiem", "size": "24 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "A Quiet Place", "size": "28 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "A Way Out", "size": "12 GB", "location": "Jackalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Ace Combat - Assault Horizon", "size": "5 GB", "location": "Corvus", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Ace Combat 7 - Skies Unknown", "size": "36 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Act of War", "size": "10 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 1 },
    { "title": "AEW - Fight Forever", "size": "12 GB", "location": "Ivonius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Age of Empire 2 - Definitive Edition", "size": "14 GB", "location": "Edius", "backup": "Nevos (Update Chronicles)", "size_jadi": "", "spec": 2 },
    { "title": "Age of Empire 3 - Classic & Definitive Edition", "size": "5 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Age of Empire 4 - Anniversary Edition", "size": "20 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Age of Mythology - Retold", "size": "8 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "AI Limit", "size": "11 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Alan Wake 2", "size": "65 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Alan Wake Remastered", "size": "22 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Alien Shooter & Zombie Shooter (All Series Collection)", "size": "9 GB", "location": "Radevius", "backup": "", "size_jadi": "", "spec": 1 },
    { "title": "Ambulance Life A Paramedic Simulator", "size": "62 GB", "location": "Lazarus", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "American Truck Simulator", "size": "15 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Anno 1800", "size": "20 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Anno 2205", "size": "11 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Anno Old (Anno 1404, 1503, 1602, 1701, 2070)", "size": "7 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "ARK - Survival Evolved", "size": "38 GB", "location": "Bravo", "backup": "Movius (Elamigos) 47GB", "size_jadi": "", "spec": 4 },
    { "title": "Arma 2 Combined Operation", "size": "13 GB", "location": "Corvus", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Arma 3", "size": "134 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Arma Reforger", "size": "9 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Armor Clash 2022", "size": "11 GB", "location": "Delta", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Armored Core VI - Fires of Rubicon", "size": "38 GB", "location": "Hybird_01", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Asetto Corsa", "size": "6 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Asetto Corsa Competizione", "size": "10 GB", "location": "Jackalius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Asetto Corsa EVO", "size": "12 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Assassin Creed 3", "size": "11 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Assassin Creed 4 - Black Flag", "size": "5 GB", "location": "Ivonius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Assassin Creed Mirage", "size": "21 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Assassin Creed Odyssey", "size": "52 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Assassin Creed Origins", "size": "37 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Assassin Creed Revelations", "size": "5 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Assassin Creed Rogue", "size": "6 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Assassin Creed Syndicate", "size": "20 GB", "location": "Alpha", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Assassin Creed Unity", "size": "32 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Assassin Creed Valhala", "size": "67 GB", "location": "Edius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Atelier Ryza 3", "size": "14 GB", "location": "Ivonius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Atlas Fallen", "size": "20 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Atomic Heart", "size": "26 GB", "location": "Corvus", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Attack on Titan 1", "size": "5 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Attack on Titan 2", "size": "20 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Automobilista 2", "size": "21 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Avatar : The Last Airbender - Quest for Balance", "size": "6 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Baldurs Gate 3", "size": "90 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Banishers - Ghost of New Eden", "size": "37 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Batman - Arkham Knight", "size": "28 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Battlefield - Hardline", "size": "23 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Battlefield 1 (2016)", "size": "16 GB", "location": "Alpha", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Battlefield 3 - Premium", "size": "23 GB", "location": "Delta", "backup": "Movius (Dodi Version)", "size_jadi": "", "spec": 3 },
    { "title": "Battlefield 4", "size": "25 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Battlefield 5", "size": "34 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Battlefield 6", "size": "90 GB", "location": "Radevius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Battlefleet Gothic Armada 1", "size": "18 GB", "location": "Edius", "backup": "Redevius (elamigos)", "size_jadi": "", "spec": 4 },
    { "title": "Beam NG Drive", "size": "43 GB", "location": "Fidelius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Berserk and The Band of the Hawk", "size": "17 GB", "location": "Hybird_01", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Beyond : Two Souls", "size": "28 GB", "location": "Lazarus", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Bio Mutant", "size": "10 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Black Mesa Definitive Edition", "size": "9 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Black Myth Wukong", "size": "141 GB", "location": "Rezevius", "backup": "", "size_jadi": "", "hypervisor": true, "spec": 6 },
    { "title": "Bleach - Rebirth of Souls", "size": "58 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Borderlands 2 Remastered", "size": "16 GB", "location": "Corvus", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Borderlands 3", "size": "60 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Bright Memory", "size": "7 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Broken Arrow", "size": "23 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Bus Simulator 21 + Euro Truck Simulator 2", "size": "10 GB", "location": "Edius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Call of Duty - Advanced Warfare", "size": "24 GB", "location": "Alpha", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Call of Duty - Black Ops 1", "size": "13 GB", "location": "Alpha", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Call of Duty - Black Ops 2", "size": "10 GB", "location": "Alpha", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Call of Duty - Black Ops 3", "size": "50 GB", "location": "Bravo", "backup": "", "size_jadi": "53 GB (Campaign Only)", "spec": 4 },
    { "title": "Call of Duty - Black Ops 4 (Multiplayer Only)", "size": "150 GB", "location": "Ivonius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Call of Duty - Black Ops 6", "size": "51 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Call of Duty - Black Ops Cold War", "size": "120 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Call of Duty - Ghost", "size": "27 GB", "location": "Alpha", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Call of Duty - Infinite Warfare", "size": "40 GB", "location": "Alpha", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Call of Duty - Modern Warfare 1 - Remastered", "size": "30GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Call of Duty - Modern Warfare 2 - Remastered", "size": "46GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Call of Duty - Modern Warfare 1, 2, 3 (Classic)", "size": "21 GB", "location": "Alpha", "backup": "MW1 (Jakcalius)", "size_jadi": "", "spec": 2 },
    { "title": "Call of Duty - Modern Warfare I Reboot (2019)", "size": "135 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Call of Duty - Modern Warfare II Reboot (2022)", "size": "33 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Call of Duty - Modern Warfare III Reboot (2023)", "size": "48 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Call of Duty - Vanguard", "size": "55 GB", "location": "Phanteon", "backup": "", "size_jadi": "68 GB", "spec": 5 },
    { "title": "Call of Duty - WWII (2017)", "size": "52 GB", "location": "Corvus", "backup": "Quetzal (Backup elamigos)", "size_jadi": "", "spec": 4 },
    { "title": "Call to Arms", "size": "14 GB", "location": "Alpha", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Call to Arms - Osfront", "size": "21 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Captain Tsubasa - Rise of New Champion", "size": "12 GB", "location": "Radevius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Car Mechanic Simulator", "size": "11 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "CarX Street", "size": "10 GB", "location": "Movius", "backup": "", "size_jadi": "15 GB", "spec": 4 },
    { "title": "Cilivization 6", "size": "9 GB", "location": "Delta", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Cities Skyline", "size": "6 GB", "location": "Fidelius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Cities Skyline 2", "size": "34 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Clair Obscur Expedition 33", "size": "38 GB", "location": "Oblivion", "backup": "", "size_jadi": "40 GB", "spec": 6 },
    { "title": "Command and Conquer REMASTERED", "size": "15 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Commandos - Origins", "size": "11 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Company of Heroes 2", "size": "15 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Company of Heroes 3", "size": "15 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Control - Ultimate Edition", "size": "26 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Counter Strike : Global Offensive (Unlock All Skin)", "size": "8 GB", "location": "Bravo", "backup": "Update Legacy (Jackalius)", "size_jadi": "", "spec": 2 },
    { "title": "Counter Strike 2 : (Unlock All Skin)", "size": "24 GB", "location": "Jackalius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Crackdown", "size": "18 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Crash Bandicot 4 - its About Time", "size": "14 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Crimeboss - Rockay City", "size": "48 GB", "location": "Lazarus", "backup": "", "size_jadi": "87 GB", "spec": 4 },
    { "title": "Crisis Core - Final Fantasy 7 - Reunion", "size": "13 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Crysis 3", "size": "8 GB", "location": "Alpha", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Crysis Remastered", "size": "11 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Cyberpunk 2077 : Liberty Phantom", "size": "77 GB", "location": "Jackalius", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Daemon X Machina", "size": "22 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Dakkar - Desert Rally", "size": "42 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Dark Souls 3", "size": "15 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Darksiders Genesis", "size": "10 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Daysgone", "size": "35 GB", "location": "Edius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Daysgone - Definitive Edition", "size": "33 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Dead Island 2", "size": "45 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Dead or Alive 5 - Last Round", "size": "5 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Dead or Alive 6", "size": "17 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Dead Rising 3 - Apocalypse Edition", "size": "13 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Dead Rising 4", "size": "20 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Death Stranding", "size": "55 GB", "location": "Ivonius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Deathloop", "size": "22 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Delta Force - Hawk Ops - Garena", "size": "100 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Demon Slayer", "size": "6 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Detroit Become Human", "size": "39 GB", "location": "Fidelius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Devil May Cry 5", "size": "27 GB", "location": "Fidelius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Die by The Blade", "size": "11 GB", "location": "Lazarus", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Dirt 2.0", "size": "103 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Dirt 4", "size": "15 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Dirt 5", "size": "20 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Disney Dreamlight", "size": "14 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Dispatch", "size": "8 GB", "location": "Radevius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Dissidia Final Fantasy", "size": "25 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Doom Eternal", "size": "55 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Dragon Age - The Veilguard", "size": "90 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Dragon Ball - Xenoverse 2", "size": "16 GB", "location": "Edius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Dragon Ball Sparking Zero", "size": "19 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Dragon Ball Xenoverse 1", "size": "8 GB", "location": "Hybird_01", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Dragon Ball Z - Kakarot", "size": "32 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Dragon Dogma 2", "size": "57 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Dragon Quest XI - Echoes of an Elusive Age", "size": "30 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Dying Light : The Beast", "size": "41 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Dying Light 1 - The Following DLC", "size": "10 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Dying Light 2", "size": "25 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Dynasty Warrior - Origins", "size": "33 GB", "location": "Nevos", "backup": "Dwupdate (Lazarus)", "size_jadi": "58 GB", "spec": 5 },
    { "title": "Dynasty Warriors 8 - Empires", "size": "9 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Dynasty Warriors 8 - Extreme Legends", "size": "6 GB", "location": "Fidelius", "backup": "Qilin (Backup elamigos)", "size_jadi": "", "spec": 2 },
    { "title": "Dynasty Warriors 9", "size": "17 GB", "location": "Corvus", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Dynasty Warriors 9 - Empires", "size": "27 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Earth Defense Force 5", "size": "9 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Earth Defense Force 6", "size": "13 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Easy Red 2", "size": "16 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Elden Ring - DLC Erdtree v1.16.1", "size": "38 GB", "location": "Gigantius", "backup": "DLC Erdtree - Qilin - 63 GB", "size_jadi": "", "spec": 5 },
    { "title": "Elden Ring - Nightrein v1.02.1", "size": "22 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Empire Total War", "size": "10 GB", "location": "Radevius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Everspace 2", "size": "21 GB", "location": "Delta", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Evil West", "size": "25 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Expedition - A MudRunner", "size": "11 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "F1 2017", "size": "35 GB", "location": "Radevius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "F1 2022", "size": "28 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Fallout - London", "size": "39 GB", "location": "Lazarus", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Fallout 3", "size": "5 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Fallout 4", "size": "21 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Farcry 3 Duology", "size": "4 GB", "location": "Bravo", "backup": "", "size_jadi": "11 GB", "spec": 3 },
    { "title": "Farcry 4", "size": "11 GB", "location": "Alpha", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Farcry 5 + New Dawn", "size": "34 GB", "location": "Alpha", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "FarCry 6", "size": "40 GB", "location": "Corvus", "backup": "", "size_jadi": "76 GB", "spec": 5 },
    { "title": "Farming Simulator 22", "size": "18 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Farming Simulator 25", "size": "17 GB", "location": "Movius", "backup": "", "size_jadi": "36 GB", "spec": 5 },
    { "title": "Farthest Frontier", "size": "2 GB", "location": "Radevius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Fatal Frame - Maiden of Black Water", "size": "13 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Fatal Frame - Mask of the Lunar Eclipse", "size": "6 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Fate - Samurai Remnant", "size": "15 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Fernbus Simulator", "size": "18 GB", "location": "Lazarus", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "FIFA 2019", "size": "23 GB", "location": "Edius", "backup": "Gigantius (Dodi Version)", "size_jadi": "", "spec": 3 },
    { "title": "FIFA 2023", "size": "50 GB", "location": "Ivonius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Final Fantasy VII Rebirth", "size": "135 GB", "location": "Lazarus", "backup": "", "size_jadi": "153 GB", "spec": 6 },
    { "title": "Final Fantasy VII Remake - Intergrade", "size": "60 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Final Fantasy XIII", "size": "29 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Final Fantasy XV", "size": "56 GB", "location": "Fidelius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Final Fantasy XVI", "size": "160 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Football Manager 2023", "size": "3 GB", "location": "Edius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Football Manager 2024 (Epic Game Share)", "size": "8 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Forspoken", "size": "90 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Forza Horizon 3", "size": "27 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Forza Horizon 4", "size": "44 GB", "location": "Movius", "backup": "Rezevius (elamigos)", "size_jadi": "84 GB", "spec": 4 },
    { "title": "Forza Horizon 5", "size": "71 GB", "location": "Edius", "backup": "Oblivion (Update)", "size_jadi": "", "spec": 5 },
    { "title": "Forza Motosport 2023", "size": "87 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Forza Motosport 7", "size": "67 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Freedom Wars - Remastered", "size": "8 GB", "location": "Hybird_01", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Frostpunk 2", "size": "8 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Gears 5 - Hivebuster", "size": "103 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Genshin Impact - Private Server (Skin Unlocked, God Mode)", "size": "48 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Ghost of Tsusima", "size": "46 GB", "location": "Nevos", "backup": "", "size_jadi": "52 GB", "spec": 3 },
    { "title": "Ghost Recon - Future Soldier", "size": "9 GB", "location": "Alpha", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Ghost Recon - Wildlands", "size": "31 GB", "location": "Bravo", "backup": "Hybird_01 (Dodi Version)", "size_jadi": "", "spec": 4 },
    { "title": "Ghost Runner 2", "size": "20 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Ghostwire - Tokyo", "size": "11 GB", "location": "Kronos", "backup": "Hybird_01 (Dodi Version)", "size_jadi": "", "spec": 5 },
    { "title": "God of War - Ragnarok", "size": "175 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "God of War 2019", "size": "28 GB", "location": "Corvus", "backup": "Gigantius (Dodi Version)", "size_jadi": "", "spec": 3 },
    { "title": "Gotham Knight", "size": "25 GB", "location": "Hybird_01", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Granblue Fantasy Relink", "size": "46 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Granblue Fantasy Versus - Rising", "size": "12 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Grid 2019", "size": "37 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "GTA IV", "size": "13 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "GTA Trilogy Remastered", "size": "21 GB", "location": "Fidelius", "backup": "", "size_jadi": "31 GB", "spec": 3 },
    { "title": "GTA V", "size": "46 GB", "location": "Alpha", "backup": "Gigantius (Dodi Version)", "size_jadi": "108 GB", "spec": 2 },
    { "title": "Gundam Breaker 4", "size": "5 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Halo Infinite", "size": "32 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Halo Wars 2", "size": "17 GB", "location": "Corvus", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Heavy Rain", "size": "10 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Hi-Fi Rush", "size": "18 GB", "location": "Radevius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Hitman - 2016", "size": "22 GB", "location": "Edius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Hitman - Absolution", "size": "12 GB", "location": "Edius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Hitman 3 - World of Assassination", "size": "56 GB", "location": "Lazarus", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Hogwart Legacy", "size": "75 GB", "location": "Edius", "backup": "", "size_jadi": "71 GB", "spec": 6 },
    { "title": "Homefront - The Revolution", "size": "20 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Hootwheels Unleashed", "size": "16 GB", "location": "Fidelius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Hootwheels Unleashed 2", "size": "10 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Horizon - Forbidden West", "size": "90 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Horizon - Zero Dawn", "size": "38 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "House Flipper 1&2", "size": "8 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Immortals Fenyx Rising", "size": "20 GB", "location": "Fidelius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Indiana Jones and the Great Circle", "size": "108 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Injustice 2", "size": "33 GB", "location": "Ivonius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Into the Dead - Our Darkest Day", "size": "6 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Inzoi - Early Acces", "size": "22 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Iron Harvest", "size": "12 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Isonzo", "size": "10 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "It Take Two", "size": "22 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Jagged Alliance 3", "size": "10 GB", "location": "Fidelius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Japanese Drift Master", "size": "13 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Judgement", "size": "22 GB", "location": "Rezevius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Jujutsu Kaisen", "size": "7 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "JUMP Force", "size": "9 GB", "location": "Rezevius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Jurassic World - Evolution", "size": "6,8 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Jurassic World - Evolution 2", "size": "6,2 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Just Cause 3 - XL Edition", "size": "18 GB", "location": "Alpha", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Just Cause 4", "size": "21 GB", "location": "Delta", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Kena - Bridge of Spirits", "size": "18 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Killzone - Trilogy (1,2,3)", "size": "58 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Kingdom Come Deliverance 2", "size": "90 GB", "location": "Lazarus", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Knight of Honor 2 : Sovereign", "size": "8 GB", "location": "Rezevius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Left for Dead 2", "size": "10 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 1 },
    { "title": "Lego 2K Drive", "size": "8 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Lego City - Undercover", "size": "19 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Lego Horizon Adventure", "size": "12 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Lego Star Wars - The Skywalker Saga", "size": "20 GB", "location": "Hybird_01", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Lies of P", "size": "26 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Life is Strange - Before the Storm", "size": "8 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Little Nightmare 1&2", "size": "7 GB", "location": "Fidelius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Little Nightmare 3", "size": "12 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Lollipop Chainsaw - Repop", "size": "12 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Mad Max", "size": "31 GB", "location": "Rezevius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "MAFIA 2 - Definitive Edition", "size": "12 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "MAFIA 3", "size": "20 GB", "location": "Ivonius", "backup": "", "size_jadi": "37GB", "spec": 4 },
    { "title": "Manor Lords", "size": "6 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Marvel Avenger", "size": "85 GB", "location": "Gigantius", "backup": "", "size_jadi": "94 GB", "spec": 5 },
    { "title": "Marvel Guardian of The Galaxy", "size": "22 GB", "location": "Fidelius", "backup": "", "size_jadi": "68 GB", "spec": 5 },
    { "title": "Marvel Spiderman 2", "size": "84 GB", "location": "Lazarus", "backup": "", "size_jadi": "107 GB", "spec": 6 },
    { "title": "Marvel Spiderman Miles Morales", "size": "28 GB", "location": "Fidelius", "backup": "Gigantius (FitGirl Version)", "size_jadi": "47 GB", "spec": 5 },
    { "title": "Marvel Spiderman Remastered", "size": "40 GB", "location": "Gigantius", "backup": "", "size_jadi": "65 GB", "spec": 5 },
    { "title": "Marvel vs Capcom - Fighting.Collection.Arcade.Classics", "size": "3 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Marvel vs Capcom - Infinity", "size": "58 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Mass Effect 3 - Legendary Edition", "size": "20 GB", "location": "Edius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Max Payne 3", "size": "13 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "MechWarrior 5 Clans", "size": "50 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Medal of Honor - Warfighter", "size": "11 GB", "location": "Alpha", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Men of War 2 Remake", "size": "20 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Men of War Assault Squad + Coldwar", "size": "6 GB", "location": "Delta", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Metal Gear Rising Revengeance", "size": "23 GB", "location": "Fidelius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Metal Gear Solid Delta - Snake Eater", "size": "73 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Metal Gear Solid V", "size": "12 Gb", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Metaphor Refantazio", "size": "28 GB", "location": "Hybird_01", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Metro Exodus", "size": "56 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Metro Redux", "size": "7 GB", "location": "Corvus", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Microsoft Flight Simulator 2016", "size": "", "location": "Rezevius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Microsoft Flight Simulator 21", "size": "68 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Microsoft Flight Simulator X", "size": "10 GB", "location": "Rezevius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Middle Earth - Shadow of War", "size": "35 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Middle Earth Shadow of Mordor", "size": "18 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Minecraft Legend", "size": "9 GB", "location": "Delta", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Monster Energy 25", "size": "15 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Monster Energy Supercross 6", "size": "11 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Monster Hunter Rise", "size": "23 GB", "location": "Ivonius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Monster Hunter Stories 2", "size": "11 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Monster Hunter World - Iceborn", "size": "34 GB", "location": "Kronos", "backup": "Movius (Dodi Version) 93GB", "size_jadi": "", "spec": 4 },
    { "title": "Monster Jam", "size": "10 GB", "location": "Lazarus", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Mortal Kombat 1 - 2023 (Steamshare)", "size": "180 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Mortal Kombat 11", "size": "95 GB", "location": "Jakckalius", "backup": "", "size_jadi": "85 GB", "spec": 4 },
    { "title": "Mortal Kombat 9 - Komplete Edition", "size": "9 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Mortal Kombat XL", "size": "23 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "MotoGP 18", "size": "8 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "MotoGP 22", "size": "17 GB", "location": "Movius", "backup": "", "size_jadi": "29 GB", "spec": 3 },
    { "title": "MotoGP 23", "size": "12 GB", "location": "Fidelius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "MotoGP 24", "size": "12 GB", "location": "Nevos", "backup": "", "size_jadi": "24 GB", "spec": 4 },
    { "title": "MotoGP 25", "size": "20 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Mount and Blade 2", "size": "22 GB", "location": "Corvus", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "MX vs ATV Legends", "size": "21 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "MXGP 2019", "size": "11 GB", "location": "Radevius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "MXGP 2021", "size": "8 GB", "location": "Fidelius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "MXGP 24", "size": "11 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Mytime at Portia + Sandrock", "size": "12 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Naruto Shippuden - Ultimate Ninja Storm 2", "size": "4 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Naruto Shippuden - Ultimate Ninja Storm 3", "size": "4 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Naruto Shippuden - Ultimate Ninja Storm 4", "size": "29 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Naruto to Boruto - Shinobi Striker", "size": "6 GB", "location": "Ivonius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Naruto X Boruto - Ultimate Ninja Storm Connections", "size": "16 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "NBA 2K22", "size": "64 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "NBA 2K23", "size": "80 GB", "location": "Jakckalius", "backup": "Movius (ISO File)", "size_jadi": "", "spec": 5 },
    { "title": "Necromunda - Hired Guns", "size": "22 GB", "location": "Rezevius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Need For Speed - Heat", "size": "21 GB", "location": "Gigantius", "backup": "Update (Oblivion)", "size_jadi": "30 GB", "spec": 3 },
    { "title": "Need For Speed - Payback", "size": "13 GB", "location": "Edius", "backup": "", "size_jadi": "27 GB", "spec": 3 },
    { "title": "Need For Speed - Rivals", "size": "7 GB", "location": "Hybird_01", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Nier Automata", "size": "20 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Nier Replicant", "size": "10 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Ninja Gaiden 2 Black", "size": "60 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Ninja Gaiden 4", "size": "52 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "No Man's Sky", "size": "7 GB", "location": "Corvus", "backup": "Update (Lazarus)", "size_jadi": "", "spec": 4 },
    { "title": "Offroad Truck Simulator", "size": "13 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "One Piece Oddysey", "size": "22 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "One Piece Pirate Warrior 3", "size": "8 GB", "location": "Hybird_01", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "One Piece Pirate Warrior 4", "size": "16 GB", "location": "Gigantius", "backup": "Ivonius (Updare)", "size_jadi": "", "spec": 3 },
    { "title": "One Piece Unlimited World", "size": "10 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Onimusha 2 - Samurai Destiny", "size": "17 GB", "location": "Radevius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Palworld", "size": "12 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Payday 2", "size": "19 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Payday 3", "size": "18 GB", "location": "Ivonius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Persona 5 - Royal", "size": "30 GB", "location": "Rezevius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "PES 2013 (Patch Februari 2025)", "size": "10 GB", "location": "Lazarus", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "PES 2017 (Patch September 2025)", "size": "22 GB", "location": "Ivonius", "backup": "Edius (PES 2017)", "size_jadi": "", "spec": 2 },
    { "title": "PES 2018", "size": "9 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "PES 2019", "size": "10 GB", "location": "Corvus", "backup": "Fidelius (Patch 2022)", "size_jadi": "", "spec": 3 },
    { "title": "PES 2021 (Patch September 2025)", "size": "90 GB", "location": "Edius", "backup": "Quetzal (Backup elamigos)", "size_jadi": "", "spec": 3 },
    { "title": "Phasmophobia", "size": "22 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Project Reality : Battlefield 2", "size": "12 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Rainbow Six - Siege", "size": "21 GB", "location": "Alpha", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Ratchet and Clank - Rift Apart", "size": "24 GB", "location": "Ivonius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Ready or Not : Supporter Edition (v39903)", "size": "92 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Red Dead Redemption 1 + Undead", "size": "9 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Red Dead Redemption 2", "size": "84 GB", "location": "Edius", "backup": "", "size_jadi": "116 GB", "spec": 3 },
    { "title": "Rematch", "size": "6 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Remnant 2", "size": "58 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Resident Evil - Bio Hazard", "size": "23 GB", "location": "Edius", "backup": "", "size_jadi": "64 GB", "spec": 3 },
    { "title": "Resident Evil - Resistance", "size": "16 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Resident Evil - Village", "size": "21 GB", "location": "Delta", "backup": "", "size_jadi": "38 GB", "spec": 3 },
    { "title": "Resident Evil 2 - Remake", "size": "17 GB", "location": "Fidelius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Resident Evil 3 - Remake", "size": "14 GB", "location": "Jakckalius", "backup": "", "size_jadi": "23 GB", "spec": 3 },
    { "title": "Resident Evil 4 - Remake", "size": "42 GB", "location": "Nevos", "backup": "", "size_jadi": "58 GB", "spec": 3 },
    { "title": "Revenge of The Savage Planet", "size": "16 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Reverse Collapse", "size": "6 GB", "location": "Lazarus", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "RIDE 4", "size": "22 GB", "location": "Hybird_01", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "RIDE 5", "size": "23 GB", "location": "Ivonius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Riders Republic", "size": "26 GB", "location": "Lazarus", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Rise of Nations - Rise of Legends", "size": "2 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Rise of The Ronin", "size": "67 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Rise of The Tomb Rider", "size": "22 GB", "location": "Rezevius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Roadcraft", "size": "54 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "RoboCop - Rogue City", "size": "29 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Rune Factory - Guardian of Azuma", "size": "11 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Saints Row - 2022", "size": "22 Gb", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Saints Row - IV", "size": "4 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Saints Row - The Third Remastered", "size": "13 Gb", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Samurai Showdown", "size": "12 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Samurai Warriors 4", "size": "10 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Samurai Warriors 5", "size": "16 GB", "location": "Lazarus", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Satisfactory", "size": "10 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "SBK 22", "size": "5 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "SD Gundam Battle Alliance", "size": "19 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "SD Gundam G Generations Cross Rays", "size": "41 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Sekiro - Shadow Die Twice", "size": "9 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Shadow of The Tomb Rider", "size": "20 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Shadow Warrior 3", "size": "16 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Silent Hill 2 - Remake", "size": "26 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Silent Hill f", "size": "40 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Six Day in Falujjah", "size": "10 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Skyrim", "size": "11 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Sleeping Dogs - Definitive Edition", "size": "10 GB", "location": "Edius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Sniper Elite 3", "size": "9 GB", "location": "Fidelius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Sniper Elite 4", "size": "27 GB", "location": "Edius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Sniper Ghost Warrior 2", "size": "9 GB", "location": "Radevius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Sniper Ghost Warrior 3", "size": "56 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Sniper Ghost Warrior Contract", "size": "11 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Sniper Ghost Warrior Contract 2", "size": "9 GB", "location": "Edius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Snowrunner - A Mudrunner Game", "size": "37 GB", "location": "Radevius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Son of The Forest", "size": "7 GB", "location": "Ivonius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Split Fiction", "size": "72 GB", "location": "Lazarus", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Spongebob - The Cosmic", "size": "4 GB", "location": "Corvus", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Spongebob - Titans of the Tide", "size": "8 GB", "location": "Radevius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "STALKER 2 - Heart of Chernobyl", "size": "111 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Star Wars - Battlefront I (2015)", "size": "30 GB", "location": "Lazarus", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Star Wars - Battlefront II (2017)", "size": "45 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Star Wars - Fallen Order", "size": "42 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Star Wars - Jedi Survivor", "size": "105 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Starcraft II - Trilogy", "size": "18 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Starfield", "size": "78 GB", "location": "Ivonius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Starship Troopers - Terran Command", "size": "7 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "State of Decay 2 - Juggernaut", "size": "12 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Steel Division 2", "size": "30 GB", "location": "Corvus", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Street Fighter V", "size": "27 GB", "location": "Hybird_01", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Stronghold - Warlord + Crusader 2", "size": "9 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Subnautica + Below Zero", "size": "10 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Suicide Squad - Kill The Justice", "size": "85 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Suikoden 1 & 2 Remastered HD", "size": "8 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Sword Art Online - Alicization Lycoris", "size": "40 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Sword Art Online Fatal Bullet - Dissonance of The Nexus Expansion", "size": "21 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Sword Art Online Last Recollection", "size": "14 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Tales of Arise", "size": "32 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Tales of Beseria", "size": "13 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Tankhead", "size": "33 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Tekken 7", "size": "40 GB", "location": "Fidelius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Tekken 8", "size": "65 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Tempest Rising", "size": "", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Terminator - Dark Fate", "size": "11 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Terminator - Resistance", "size": "14 GB", "location": "Corvus", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "The Crew 1", "size": "22 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "The Crew 2", "size": "29 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "The Dark Picture Anthology - House of Ashes", "size": "18 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "The Dark Picture Anthology - Little Hope", "size": "20 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "The Dark Picture Anthology - Man of Medan", "size": "20 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "The Dark Picture Anthology - The Devil in Me", "size": "26 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "The Elder Scrolls IV: Oblivion Remastered", "size": "113 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "The Evil Within", "size": "18 GB", "location": "Jackalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "The Evil Within 2", "size": "12 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "The Great War - Eastern Front", "size": "9 GB", "location": "Lazarus", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "The Last Of Us Part 1", "size": "43 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "The Last Of Us Part 2 - Remastered", "size": "75 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "The Legend of Heroes Trials Through Daybreaks", "size": "15 GB", "location": "Lazarus", "backup": "", "size_jadi": "15 GB", "spec": 4 },
    { "title": "The Sims 3", "size": "15 GB", "location": "Alpha", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "The Sims 4 Deluxe Edition (v1.103.250.1020)", "size": "33 GB", "location": "Edius", "backup": "Update (Kronos)", "size_jadi": "", "spec": 3 },
    { "title": "The Witcher 3", "size": "33 GB", "location": "Gigantius", "backup": "Update Wild Hunt (Nevos)", "size_jadi": "", "spec": 3 },
    { "title": "Titanfall 2", "size": "20 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Tony Hawk Pro Skater 1+2", "size": "22 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Tony Hawk Pro Skater 3+4", "size": "48 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Total Conflict", "size": "21 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Total War - Attila", "size": "11 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Total War - Imperial Edition", "size": "11 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Total War - Shogun", "size": "10 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Total War - Shogun 2", "size": "13 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Total War - Three Kingdom + Rome 2", "size": "25 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Total War - Throne of Britania", "size": "6 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Tour De France 2022", "size": "16 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Tour De France 2023", "size": "15 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Train Sim Word 4", "size": "28 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Train Sim Word 5", "size": "124 GB", "location": "Lazarus", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Trial Rising", "size": "25 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Tropico 6", "size": "15 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Troublemaker", "size": "17 GB", "location": "Delta", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Ultimate Fishing Simulator", "size": "4 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Ultra Street Fighter IV", "size": "5 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Uncharted Legacy of Thieves", "size": "65 GB", "location": "Hybird_01", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Upin Ipin Universe", "size": "6 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Virtua Fighter 5 REVO", "size": "10 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Warcraft 3 Reforged", "size": "18 GB", "location": "Ivonius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Wargame : European Escalation", "size": "5 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 2 },
    { "title": "Wargame : Red Dragon", "size": "8 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Warhammer - Dawn of War Trilogy (1,2,3)", "size": "51 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Warhammer 4000 - Battlesector", "size": "5 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Warhammer 4000 - Inquistor Martyr", "size": "20 GB", "location": "Kronos", "backup": "", "size_jadi": "78 GB", "spec": 4 },
    { "title": "Warhammer 4000 - Rogue Trader", "size": "15 GB", "location": "Kronos", "backup": "", "size_jadi": "40 GB", "spec": 4 },
    { "title": "Warhammer 4000 - Space Marine 2", "size": "41 GB", "location": "Movius", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "WARNO - Warning Operations", "size": "28 GB", "location": "Delta", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Watch Dog", "size": "13 GB", "location": "Bravo", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Watch Dog 2", "size": "22 GB", "location": "Bravo", "backup": "", "size_jadi": "25 GB", "spec": 4 },
    { "title": "Watch Dog Legion", "size": "40 GB", "location": "Edius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Wo Long - Fallen Dynasty", "size": "28 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "Wolfenstein New Colossus", "size": "38 GB", "location": "Delta", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Wolfenstein Young Blood", "size": "29 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "World War Z - Aftermath", "size": "24 GB", "location": "Corvus", "backup": "Oblivion (Update)", "size_jadi": "", "spec": 4 },
    { "title": "WRC 10", "size": "20 GB", "location": "Kronos", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "WRC 5", "size": "17 GB", "location": "Lazarus", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "WRC Generation", "size": "22 GB", "location": "Gigantius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "WRC Rally 9", "size": "12 GB", "location": "Fidelius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Wuchang - Fallen Feather", "size": "16 GB", "location": "Phanteon", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "WWE 2020", "size": "41 GB", "location": "Fidelius", "backup": "", "size_jadi": "50 GB", "spec": 4 },
    { "title": "WWE 2023", "size": "67 GB", "location": "Fidelius", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "WWE 2K15", "size": "67 GB", "location": "Nevos", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "WWE 2k19", "size": "43 GB", "location": "Oblivion", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "WWE 2K24", "size": "78 GB", "location": "Lazarus", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "WWE 2K25", "size": "80 GB", "location": "Quetzal", "backup": "", "size_jadi": "", "spec": 5 },
    { "title": "X4 Foundation", "size": "34 GB", "location": "Radevius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Yakuza 5 Remastered", "size": "13 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 3 },
    { "title": "Yakuza 6 - The Song of Life", "size": "25 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Yakuza Kimawi 2", "size": "34 GB", "location": "Jakckalius", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Yakuza Like a Dragon", "size": "27 GB", "location": "Delta", "backup": "", "size_jadi": "", "spec": 4 },
    { "title": "Nioh 3", "size": "", "location": "Rezevius", "backup": "", "size_jadi": "", "spec": 6 },
    { "title": "Resident Evil Revelation 1&2", "size": "16 GB", "location": "Rezevius", "backup": "", "size_jadi": "26 GB", "spec": 3 },
    { "title": "Resident Evil 6", "size": "10 GB", "location": "Rezevius", "backup": "", "size_jadi": "13 GB", "spec": 3 },
    { "title": "Assassin Creed Shadow", "size": "97 GB", "location": "Stradeon", "backup": "", "size_jadi": "", "hypervisor": true, "spec": 5 },
    { "title": "EA FC 26", "size": "57 GB", "location": "Stradeon", "backup": "", "size_jadi": "", "hypervisor": true, "spec": 5 },
    { "title": "Resident Evil - Requiem", "size": "71 GB", "location": "Stradeon", "backup": "", "size_jadi": "76 GB", "spec": 4 },
  ],
  "PS4": [
    { "title": "#Assassin Creed - Valhalla", "size": "110 GB", "location": "SaveStation_02", "backup": "", "size_jadi": "" },
    { "title": "#Infamous 2 - Second Son", "size": "22 GB", "location": "SaveStation_02", "backup": "", "size_jadi": "" },
    { "title": "#Like a Dragon - Infinite Wealth", "size": "60 GB", "location": "SaveStation_02", "backup": "", "size_jadi": "" },
    { "title": "#Need For Speed - Heat", "size": "32 GB", "location": "SaveStation_02", "backup": "", "size_jadi": "" },
    { "title": "#Resident Evil 4 Remake - Separate Ways DLC", "size": "40 GB", "location": "SaveStation_02", "backup": "", "size_jadi": "" },
    { "title": "#Wolfenstein - New Order", "size": "42 GB", "location": "SaveStation_02", "backup": "", "size_jadi": "" },
    { "title": "A Way Out", "size": "16 GB", "location": "Nevos", "backup": "", "size_jadi": "" },
    { "title": "Assassin Creed - Mirage", "size": "27 GB", "location": "Kronos", "backup": "", "size_jadi": "" },
    { "title": "Assassin Creed - Origins", "size": "50 GB", "location": "SaveStation_01", "backup": "", "size_jadi": "" },
    { "title": "Borderland The Handsome Collection", "size": "37 GB", "location": "Nevos", "backup": "", "size_jadi": "" },
    { "title": "Call of Duty - Black Ops 6", "size": "87 GB", "location": "Nevos", "backup": "", "size_jadi": "" },
    { "title": "Call of Duty - Modern Warfare 1 (reboot)", "size": "80 GB", "location": "SaveStation_01 + Livion (DLC)", "backup": "", "size_jadi": "" },
    { "title": "Call of Duty - Modern Warfare 3 (reboot)", "size": "70 GB", "location": "Kronos", "backup": "", "size_jadi": "" },
    { "title": "Call of Duty - Vanguard", "size": "72 GB", "location": "Kronos", "backup": "", "size_jadi": "" },
    { "title": "Crash Bandicot 4", "size": "40 GB", "location": "Quetzal", "backup": "", "size_jadi": "" },
    { "title": "CTR - Nitro Fueled", "size": "21 GB", "location": "Quetzal", "backup": "", "size_jadi": "" },
    { "title": "Cyberpunk 2077", "size": "62 GB", "location": "Movius", "backup": "", "size_jadi": "" },
    { "title": "Demon Slayer 2", "size": "21 GB", "location": "Quetzal", "backup": "", "size_jadi": "" },
    { "title": "Divinity Original Sin 2", "size": "20 GB", "location": "Nevos", "backup": "", "size_jadi": "" },
    { "title": "Dynasty Warrior 9 Empires", "size": "35 GB", "location": "Pantheon", "backup": "", "size_jadi": "" },
    { "title": "EAFC 24/FIFA24", "size": "44 GB", "location": "Kronos", "backup": "", "size_jadi": "" },
    { "title": "EAFC 25/FIFA25", "size": "45 GB", "location": "Movius", "backup": "", "size_jadi": "" },
    { "title": "EAFC 26/FIFA26", "size": "75 GB", "location": "Quetzal", "backup": "", "size_jadi": "" },
    { "title": "Earth Defense Force 6", "size": "48 GB", "location": "Nevos", "backup": "", "size_jadi": "" },
    { "title": "Everybody Golf", "size": "7 GB", "location": "Nevos", "backup": "", "size_jadi": "" },
    { "title": "Far Cry 6", "size": "102 GB", "location": "SaveStation_01", "backup": "", "size_jadi": "" },
    { "title": "Ghost of Tsusima", "size": "42 GB", "location": "Hybird_01", "backup": "", "size_jadi": "" },
    { "title": "God Of War Ragnarog - Valhalla DLC", "size": "116 GB", "location": "SaveStation_01", "backup": "", "size_jadi": "" },
    { "title": "Grand Theft Auto 5 - Mod 2 Player", "size": "84 GB", "location": "Lazarus", "backup": "", "size_jadi": "" },
    { "title": "GranTurismo", "size": "", "location": "Hybird_01", "backup": "", "size_jadi": "" },
    { "title": "Hogwart Legacy", "size": "70 GB", "location": "Movius", "backup": "", "size_jadi": "" },
    { "title": "Horizon - Zero Dawn", "size": "47 GB", "location": "SaveStation_01", "backup": "", "size_jadi": "" },
    { "title": "Hotwheels Unleashed 2", "size": "21 GB", "location": "SaveStation_01", "backup": "", "size_jadi": "" },
    { "title": "Jujutsu Kaisen - Cursed Clash", "size": "22 GB", "location": "SaveStation_01", "backup": "", "size_jadi": "" },
    { "title": "Killzone Shadow Fall", "size": "", "location": "", "backup": "", "size_jadi": "" },
    { "title": "Lies of P", "size": "On Progress", "location": "Kronos", "backup": "", "size_jadi": "" },
    { "title": "Minecraft - PS 4 Edition", "size": "2 GB", "location": "Kronos", "backup": "", "size_jadi": "" },
    { "title": "Mortal Kombat 11", "size": "71 GB", "location": "Pantheon", "backup": "", "size_jadi": "" },
    { "title": "Mortal Kombat XL", "size": "45 GB", "location": "Movius", "backup": "", "size_jadi": "" },
    { "title": "MotoGP 22", "size": "40 GB", "location": "SaveStation_01", "backup": "", "size_jadi": "" },
    { "title": "MotoGP 24", "size": "39 GB", "location": "Movius", "backup": "", "size_jadi": "" },
    { "title": "Moving Out", "size": "1 GB", "location": "Nevos", "backup": "", "size_jadi": "" },
    { "title": "Naruto X Boruto - Ultimate Ninja Storm Connections", "size": "28 GB", "location": "SaveStation_01", "backup": "", "size_jadi": "" },
    { "title": "One Piece Pirate Warriors 4", "size": "31 GB", "location": "SaveStation_01", "backup": "", "size_jadi": "" },
    { "title": "Overcooked 2", "size": "8,5 GB", "location": "Kronos", "backup": "", "size_jadi": "" },
    { "title": "PES 2021 Patch 2026 - Monster Patch", "size": "90 GB", "location": "Quetzal", "backup": "", "size_jadi": "" },
    { "title": "Plant vs Zombie - Replanted", "size": "2 GB", "location": "Quetzal", "backup": "", "size_jadi": "" },
    { "title": "Prince of Persia - The Lost Crown", "size": "10 GB", "location": "Kronos", "backup": "", "size_jadi": "" },
    { "title": "Red Dead Redemption 2", "size": "98 GB", "location": "Rezevius", "backup": "", "size_jadi": "" },
    { "title": "Resident Evil 5", "size": "15 GB", "location": "Nevos", "backup": "", "size_jadi": "" },
    { "title": "Ride 4", "size": "20 GB", "location": "Livion", "backup": "", "size_jadi": "" },
    { "title": "Rocket League", "size": "31 GB", "location": "Nevos", "backup": "", "size_jadi": "" },
    { "title": "Sackboy", "size": "33 GB", "location": "Nevos", "backup": "", "size_jadi": "" },
    { "title": "Samurai Warrioir 5", "size": "12 GB", "location": "Nevos", "backup": "", "size_jadi": "" },
    { "title": "Sniper Elite - Resistance", "size": "46 GB", "location": "Lazarus", "backup": "", "size_jadi": "" },
    { "title": "Spiderman - Miles Morales", "size": "46 GB", "location": "SaveStation_01", "backup": "", "size_jadi": "" },
    { "title": "Star Wars - Jedi Survivor", "size": "51 GB", "location": "Lazarus", "backup": "", "size_jadi": "" },
    { "title": "Street Fighter 6", "size": "40 GB", "location": "SaveStation_01", "backup": "", "size_jadi": "" },
    { "title": "TonyHawk 0+1", "size": "71 GB", "location": "Nevos", "backup": "", "size_jadi": "" },
    { "title": "UFC 4", "size": "26 GB", "location": "SaveStation_01", "backup": "", "size_jadi": "" },
    { "title": "Watch Dog Legion - Bloodline DLC", "size": "46 GB", "location": "SaveStation_01", "backup": "", "size_jadi": "" },
    { "title": "Upin dan Ipin Universe", "size": "6 GB", "location": "Pantheon", "backup": "", "size_jadi": "" },
    { "title": "Need For Seped - Heat", "size": "", "location": "", "backup": "", "size_jadi": "" },

  ]
};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { RAW_DB };
}
